//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleFileServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_TELEEntities : DbContext
    {
        public DB_TELEEntities()
            : base("name=DB_TELEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Admin> TB_Admin { get; set; }
        public virtual DbSet<TB_Goods> TB_Goods { get; set; }
        public virtual DbSet<TB_Order> TB_Order { get; set; }
        public virtual DbSet<TB_Broad> TB_Broad { get; set; }
        public virtual DbSet<TB_POST> TB_POST { get; set; }
        public virtual DbSet<TB_USER> TB_USER { get; set; }
        public virtual DbSet<TB_RECOMMEND> TB_RECOMMEND { get; set; }
    }
}
